### ISSUE TITLE
Better error messages

### ISSUE THREAD

**Issue by henryiii** [hukkinj1/tomli#9]
I was just testing this on a malformed toml file:

```toml
[tool.a]
hi = 1
ho = 2
[tool.*]
ho = 2
he = 3
```

`toml` gave a nice error message:

```pytb
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/henryschreiner/git/software/cibuildwheel/venv/lib/python3.9/site-packages/toml/decoder.py", line 134, in load
    return loads(ffile.read(), _dict, decoder)
  File "/Users/henryschreiner/git/software/cibuildwheel/venv/lib/python3.9/site-packages/toml/decoder.py", line 455, in loads
    raise TomlDecodeError("Invalid group name '" +
toml.decoder.TomlDecodeError: Invalid group name '*'. Try quoting it. (line 4 column 1 char 23)
```

But `tomli` just gave:

```pytb
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/henryschreiner/git/software/cibuildwheel/venv/lib/python3.9/site-packages/tomli/_parser.py", line 53, in load
    return loads(s, parse_float=parse_float)
  File "/Users/henryschreiner/git/software/cibuildwheel/venv/lib/python3.9/site-packages/tomli/_parser.py", line 91, in loads
    create_dict_rule(state)
  File "/Users/henryschreiner/git/software/cibuildwheel/venv/lib/python3.9/site-packages/tomli/_parser.py", line 229, in create_dict_rule
    key = parse_key(state)
  File "/Users/henryschreiner/git/software/cibuildwheel/venv/lib/python3.9/site-packages/tomli/_parser.py", line 309, in parse_key
    key.append(parse_key_part(state))
  File "/Users/henryschreiner/git/software/cibuildwheel/venv/lib/python3.9/site-packages/tomli/_parser.py", line 328, in parse_key_part
    raise TOMLDecodeError("Invalid key definition")
tomli._parser.TOMLDecodeError: Invalid key definition
```

Unlike `toml`, there's no location for the error, and no indication of what failed either.

**Comment by hukkinj1** [comment]
Haha one of us must have some psychic abilites. Please see https://github.com/hukkinj1/tomli/pull/8 :smile:

**Comment by hukkinj1** [comment]
Thanks for reporting! https://github.com/hukkinj1/tomli/pull/8 will add line number and column in all errors where applicable. It also improves wording of the specific error you mentioned. I will close this when that is released. If you find more bad error messages, PRs or further issues are much appreciated!
